### ISSUE TITLE
 The token is null when the callback menthod is called, an exception is thrown.

### ISSUE THREAD

**Issue by wulei-git** [ONLYOFFICE/docs-integration-sdk-java#21]
<img width="1275" alt="截屏2024-02-29 上午9 34 30" src="https://github.com/ONLYOFFICE/docs-integration-sdk-java/assets/33931048/0073199c-397d-4527-a806-ff801a8b615f">
<img width="1289" alt="截屏2024-02-29 上午9 45 21" src="https://github.com/ONLYOFFICE/docs-integration-sdk-java/assets/33931048/f6d045fc-a9ef-44d4-8300-b55a9eff3097">

**Comment by aleksandrfedorov97** [comment]
Hello [wulei-git](https://github.com/wulei-git), is jwt enabled on the document server side? [Configuring JWT for ONLYOFFICE Docs](https://helpcenter.onlyoffice.com/installation/docs-configure-jwt.aspx)

**Comment by wulei-git** [comment]
Thank you. it works.
